### ISSUE TITLE
アプリ名を決める

### ISSUE THREAD

**Issue by saitokazumasa** [saitokazumasa/graduation-research#3]
アプリ名、アイコン名を「かわいい」「気になる」「使いたい」となるようなものに決めたい。

**Comment by saitokazumasa** [comment]
案を下につらつら載せていきます。

**Comment by saitokazumasa** [comment]
たびスケッチ

**Comment by BruinJr** [comment]
WanderBelle(ワンダーベル)
「Wander（さまよう）」と「Belle（美しい女性）」を組み合わせた名前で、素敵な旅の計画をおしゃれにサポートするイメージです。

**Comment by saitokazumasa** [comment]
アプリ名は「たびすけっち」に決定
